import {
  Patient,
  Exercise,
  ExerciseCategory,
  Protocol,
  ExerciseSession,
  Appointment,
  RomDataPoint,
  ClinicalNote,
  AppNotification,
  VideoReview,

  ComplianceDataPoint,
  TreatmentHistoryEntry,
  User,
} from "@/types";

export const currentUser: User = {
  id: "u1",
  email: "dr.nguyen@hopita.vn",
  fullName: "BS. Nguyen Van An",
  phone: "0901234567",
  avatarUrl: undefined,
  role: "doctor",
  facilityId: "f1",
  createdAt: "2024-01-15",
};

export const patients: Patient[] = [
  {
    id: "p1",
    fullName: "Tran Thi Mai",
    email: "mai.tran@gmail.com",
    phone: "0912345678",
    dateOfBirth: "1985-03-15",
    gender: "female",
    diagnosis: "Phục hồi sau phẫu thuật dây chằng chéo trước (ACL)",
    status: "active",
    assignedDoctorId: "u1",
    assignedDoctorName: "BS. Nguyen Van An",
    currentProtocolId: "pr1",
    currentProtocolName: "Phục hồi ACL - Giai đoạn 2",
    complianceRate: 85,
    lastSessionAt: "2025-02-10T14:30:00",
    createdAt: "2024-11-01",
  },
  {
    id: "p2",
    fullName: "Le Hoang Nam",
    email: "nam.le@gmail.com",
    phone: "0923456789",
    dateOfBirth: "1990-07-22",
    gender: "male",
    diagnosis: "Đau lưng mạn tính - Thoát vị đĩa đệm L4-L5",
    status: "active",
    assignedDoctorId: "u1",
    assignedDoctorName: "BS. Nguyen Van An",
    currentProtocolId: "pr2",
    currentProtocolName: "Phục hồi cột sống thắt lưng",
    complianceRate: 72,
    lastSessionAt: "2025-02-09T10:00:00",
    createdAt: "2024-12-15",
  },
  {
    id: "p3",
    fullName: "Pham Duc Minh",
    email: "minh.pham@gmail.com",
    phone: "0934567890",
    dateOfBirth: "1978-11-30",
    gender: "male",
    diagnosis: "Đông cứng khớp vai (Frozen shoulder)",
    status: "attention",
    assignedDoctorId: "u1",
    assignedDoctorName: "BS. Nguyen Van An",
    currentProtocolId: "pr3",
    currentProtocolName: "Phục hồi khớp vai",
    complianceRate: 45,
    lastSessionAt: "2025-02-05T09:00:00",
    createdAt: "2024-10-20",
    notes: "Bệnh nhân bỏ tập 5 ngày liên tiếp",
  },
  {
    id: "p4",
    fullName: "Nguyen Thi Lan",
    email: "lan.nguyen@gmail.com",
    phone: "0945678901",
    dateOfBirth: "1995-05-10",
    gender: "female",
    diagnosis: "Chấn thương cơ vai khi chơi cầu lông",
    status: "completed",
    assignedDoctorId: "u1",
    assignedDoctorName: "BS. Nguyen Van An",
    complianceRate: 95,
    lastSessionAt: "2025-01-28T16:00:00",
    createdAt: "2024-09-01",
  },
  {
    id: "p5",
    fullName: "Vo Van Tai",
    email: "tai.vo@gmail.com",
    phone: "0956789012",
    dateOfBirth: "1982-01-25",
    gender: "male",
    diagnosis: "Phục hồi sau thay khớp gối",
    status: "active",
    assignedDoctorId: "u1",
    assignedDoctorName: "BS. Nguyen Van An",
    currentProtocolId: "pr4",
    currentProtocolName: "Phục hồi thay khớp gối - Giai đoạn 1",
    complianceRate: 90,
    lastSessionAt: "2025-02-10T08:30:00",
    createdAt: "2025-01-10",
  },
  {
    id: "p6",
    fullName: "Hoang Thi Huong",
    email: "huong.hoang@gmail.com",
    phone: "0967890123",
    dateOfBirth: "1988-09-18",
    gender: "female",
    diagnosis: "Hội chứng ống cổ tay (Carpal tunnel)",
    status: "active",
    assignedDoctorId: "u1",
    assignedDoctorName: "BS. Nguyen Van An",
    currentProtocolId: "pr5",
    currentProtocolName: "Phục hồi ống cổ tay",
    complianceRate: 78,
    lastSessionAt: "2025-02-09T15:00:00",
    createdAt: "2025-01-05",
  },
  {
    id: "p7",
    fullName: "Dang Quoc Bao",
    email: "bao.dang@gmail.com",
    phone: "0978901234",
    dateOfBirth: "2000-12-05",
    gender: "male",
    diagnosis: "Bong gân cổ chân sau chơi bóng đá",
    status: "attention",
    assignedDoctorId: "u1",
    assignedDoctorName: "BS. Nguyen Van An",
    currentProtocolId: "pr6",
    currentProtocolName: "Phục hồi cổ chân",
    complianceRate: 35,
    lastSessionAt: "2025-02-03T11:00:00",
    createdAt: "2025-01-20",
    notes: "Bệnh nhân tập sai tư thế nhiều lần",
  },
  {
    id: "p8",
    fullName: "Bui Thi Thanh",
    email: "thanh.bui@gmail.com",
    phone: "0989012345",
    dateOfBirth: "1972-04-08",
    gender: "female",
    diagnosis: "Thoái hóa khớp gối",
    status: "active",
    assignedDoctorId: "u1",
    assignedDoctorName: "BS. Nguyen Van An",
    currentProtocolId: "pr7",
    currentProtocolName: "Bài tập thoái hóa khớp gối",
    complianceRate: 88,
    lastSessionAt: "2025-02-10T10:00:00",
    createdAt: "2024-08-15",
  },
];

export const exercises: Exercise[] = [
  {
    id: "e1",
    name: "Gập gối (Knee Flexion)",
    description: "Gập gối từ từ để tăng biên độ vận động khớp gối",
    videoUrl: "/videos/knee-flexion.mp4",
    durationSeconds: 30,
    repetitions: 15,
    setsPerDay: 3,
    safetyNotes: "Dừng gập quá 90 độ trong giai đoạn đầu",
    category: "Khớp gối",
  },
  {
    id: "e2",
    name: "Duỗi gối (Knee Extension)",
    description: "Duỗi thẳng chân để tăng sức mạnh cơ tứ đầu",
    videoUrl: "/videos/knee-extension.mp4",
    durationSeconds: 30,
    repetitions: 12,
    setsPerDay: 3,
    safetyNotes: "Giữ lưng thẳng, không uốn cong",
    category: "Khớp gối",
  },
  {
    id: "e3",
    name: "Nâng chân thẳng (Straight Leg Raise)",
    description: "Nâng chân thẳng khi nằm ngửa để tăng sức cơ",
    videoUrl: "/videos/slr.mp4",
    durationSeconds: 20,
    repetitions: 10,
    setsPerDay: 3,
    category: "Khớp gối",
  },
  {
    id: "e4",
    name: "Xoay vai (Shoulder Rotation)",
    description: "Xoay vai theo vòng tròn để tăng ROM",
    videoUrl: "/videos/shoulder-rotation.mp4",
    durationSeconds: 25,
    repetitions: 10,
    setsPerDay: 2,
    safetyNotes: "Không xoay quá nhanh",
    category: "Khớp vai",
  },
  {
    id: "e5",
    name: "Căng cơ bắp chân (Calf Stretch)",
    description: "Kéo giãn cơ bắp chân để giảm đau và tăng độ linh hoạt",
    videoUrl: "/videos/calf-stretch.mp4",
    durationSeconds: 30,
    repetitions: 8,
    setsPerDay: 2,
    category: "Cổ chân",
  },
  {
    id: "e6",
    name: "Plank cơ bản",
    description: "Bài tập plank tăng sức mạnh cơ lõi (core)",
    videoUrl: "/videos/plank.mp4",
    durationSeconds: 30,
    repetitions: 3,
    setsPerDay: 2,
    safetyNotes: "Giữ lưng thẳng, không võng lưng",
    category: "Cột sống",
  },
  {
    id: "e7",
    name: "Cat-Cow Stretch",
    description: "Kéo giãn cột sống theo kiểu mèo-bò",
    videoUrl: "/videos/cat-cow.mp4",
    durationSeconds: 20,
    repetitions: 10,
    setsPerDay: 2,
    category: "Cột sống",
  },
  {
    id: "e8",
    name: "Bài tập cổ tay (Wrist Flexion)",
    description: "Gập duỗi cổ tay để phục hồi hội chứng ống cổ tay",
    videoUrl: "/videos/wrist-flexion.mp4",
    durationSeconds: 15,
    repetitions: 15,
    setsPerDay: 3,
    category: "Cổ tay",
  },
];

export const exerciseCategories: ExerciseCategory[] = [
  { id: "cat1", name: "Khớp gối", description: "Bài tập phục hồi chức năng khớp gối", exerciseCount: 3, createdAt: "2024-01-15" },
  { id: "cat2", name: "Khớp vai", description: "Bài tập phục hồi chức năng khớp vai", exerciseCount: 1, createdAt: "2024-01-15" },
  { id: "cat3", name: "Cổ chân", description: "Bài tập phục hồi chức năng cổ chân", exerciseCount: 1, createdAt: "2024-01-15" },
  { id: "cat4", name: "Cột sống", description: "Bài tập phục hồi chức năng cột sống", exerciseCount: 2, createdAt: "2024-02-01" },
  { id: "cat5", name: "Cổ tay", description: "Bài tập phục hồi chức năng cổ tay", exerciseCount: 1, createdAt: "2024-03-10" },
];

export const protocols: Protocol[] = [
  {
    id: "pr1",
    name: "Phục hồi ACL - Giai đoạn 2",
    description: "Phác đồ phục hồi sau phẫu thuật dây chằng chéo trước, giai đoạn 2 (tuần 4-8)",
    targetCondition: "ACL Reconstruction",
    isTemplate: true,
    exercises: [
      { exerciseId: "e1", exerciseName: "Gập gối", sets: 3, reps: 15, durationSeconds: 30, frequency: "2 lần/ngày", order: 1 },
      { exerciseId: "e2", exerciseName: "Duỗi gối", sets: 3, reps: 12, durationSeconds: 30, frequency: "2 lần/ngày", order: 2 },
      { exerciseId: "e3", exerciseName: "Nâng chân thẳng", sets: 3, reps: 10, durationSeconds: 20, frequency: "1 lần/ngày", order: 3 },
    ],
    durationWeeks: 4,
    createdBy: "BS. Nguyen Van An",
    createdAt: "2024-10-01",
    assignedPatientCount: 3,
  },
  {
    id: "pr2",
    name: "Phục hồi cột sống thắt lưng",
    description: "Phác đồ cho bệnh nhân thoát vị đĩa đệm L4-L5",
    targetCondition: "Lumbar Disc Herniation",
    isTemplate: true,
    exercises: [
      { exerciseId: "e6", exerciseName: "Plank cơ bản", sets: 2, reps: 3, durationSeconds: 30, frequency: "1 lần/ngày", order: 1 },
      { exerciseId: "e7", exerciseName: "Cat-Cow Stretch", sets: 2, reps: 10, durationSeconds: 20, frequency: "2 lần/ngày", order: 2 },
    ],
    durationWeeks: 6,
    createdBy: "BS. Nguyen Van An",
    createdAt: "2024-11-15",
    assignedPatientCount: 2,
  },
  {
    id: "pr3",
    name: "Phục hồi khớp vai",
    description: "Phác đồ cho đông cứng khớp vai (frozen shoulder)",
    targetCondition: "Frozen Shoulder",
    isTemplate: true,
    exercises: [
      { exerciseId: "e4", exerciseName: "Xoay vai", sets: 2, reps: 10, durationSeconds: 25, frequency: "3 lần/ngày", order: 1 },
    ],
    durationWeeks: 8,
    createdBy: "BS. Nguyen Van An",
    createdAt: "2024-09-20",
    assignedPatientCount: 1,
  },
  {
    id: "pr4",
    name: "Phục hồi thay khớp gối - Giai đoạn 1",
    description: "Phác đồ giai đoạn đầu sau phẫu thuật thay khớp gối (tuần 1-4)",
    targetCondition: "Total Knee Replacement",
    isTemplate: true,
    exercises: [
      { exerciseId: "e1", exerciseName: "Gập gối", sets: 2, reps: 10, durationSeconds: 30, frequency: "3 lần/ngày", order: 1 },
      { exerciseId: "e2", exerciseName: "Duỗi gối", sets: 2, reps: 10, durationSeconds: 30, frequency: "3 lần/ngày", order: 2 },
    ],
    durationWeeks: 4,
    createdBy: "BS. Nguyen Van An",
    createdAt: "2025-01-10",
    assignedPatientCount: 1,
  },
  {
    id: "pr5",
    name: "Phục hồi ống cổ tay",
    description: "Phác đồ cho hội chứng ống cổ tay (carpal tunnel)",
    targetCondition: "Carpal Tunnel Syndrome",
    isTemplate: false,
    exercises: [
      { exerciseId: "e8", exerciseName: "Bài tập cổ tay", sets: 3, reps: 15, durationSeconds: 15, frequency: "3 lần/ngày", order: 1 },
    ],
    durationWeeks: 6,
    createdBy: "BS. Nguyen Van An",
    createdAt: "2025-01-05",
    assignedPatientCount: 1,
  },
];

export const sessions: ExerciseSession[] = [
  { id: "s1", patientId: "p1", patientName: "Tran Thi Mai", exerciseId: "e1", exerciseName: "Gập gối", scheduledAt: "2025-02-10T08:00:00", completedAt: "2025-02-10T08:25:00", status: "completed", score: 88, accuracy: 92, postureScore: 85, durationSeconds: 1500, romValue: 95 },
  { id: "s2", patientId: "p1", patientName: "Tran Thi Mai", exerciseId: "e2", exerciseName: "Duỗi gối", scheduledAt: "2025-02-10T08:30:00", completedAt: "2025-02-10T08:50:00", status: "completed", score: 90, accuracy: 95, postureScore: 88, durationSeconds: 1200, romValue: 170 },
  { id: "s3", patientId: "p2", patientName: "Le Hoang Nam", exerciseId: "e6", exerciseName: "Plank cơ bản", scheduledAt: "2025-02-10T09:00:00", status: "pending" },
  { id: "s4", patientId: "p3", patientName: "Pham Duc Minh", exerciseId: "e4", exerciseName: "Xoay vai", scheduledAt: "2025-02-10T10:00:00", status: "skipped" },
  { id: "s5", patientId: "p5", patientName: "Vo Van Tai", exerciseId: "e1", exerciseName: "Gập gối", scheduledAt: "2025-02-10T08:30:00", completedAt: "2025-02-10T08:55:00", status: "completed", score: 92, accuracy: 94, postureScore: 90, durationSeconds: 1500, romValue: 85 },
  { id: "s6", patientId: "p7", patientName: "Dang Quoc Bao", exerciseId: "e5", exerciseName: "Căng cơ bắp chân", scheduledAt: "2025-02-10T11:00:00", status: "skipped" },
];

export const appointments: Appointment[] = [
  { id: "a1", patientId: "p1", patientName: "Tran Thi Mai", doctorId: "u1", doctorName: "BS. Nguyen Van An", scheduledAt: "2025-02-12T09:00:00", durationMinutes: 30, status: "scheduled", type: "followup", notes: "Tái khám sau 4 tuần tập" },
  { id: "a2", patientId: "p3", patientName: "Pham Duc Minh", doctorId: "u1", doctorName: "BS. Nguyen Van An", scheduledAt: "2025-02-12T10:00:00", durationMinutes: 45, status: "confirmed", type: "telehealth", meetingUrl: "https://meet.hopita.vn/room-123" },
  { id: "a3", patientId: "p5", patientName: "Vo Van Tai", doctorId: "u1", doctorName: "BS. Nguyen Van An", scheduledAt: "2025-02-13T14:00:00", durationMinutes: 30, status: "scheduled", type: "followup" },
  { id: "a4", patientId: "p7", patientName: "Dang Quoc Bao", doctorId: "u1", doctorName: "BS. Nguyen Van An", scheduledAt: "2025-02-14T08:30:00", durationMinutes: 60, status: "scheduled", type: "initial", notes: "Đánh giá lần đầu" },
  { id: "a5", patientId: "p2", patientName: "Le Hoang Nam", doctorId: "u1", doctorName: "BS. Nguyen Van An", scheduledAt: "2025-02-15T11:00:00", durationMinutes: 30, status: "scheduled", type: "telehealth", meetingUrl: "https://meet.hopita.vn/room-456" },
];

export const romData: RomDataPoint[] = [
  { date: "2024-11-01", value: 45, baseline: 45 },
  { date: "2024-11-15", value: 55, baseline: 45 },
  { date: "2024-12-01", value: 68, baseline: 45 },
  { date: "2024-12-15", value: 75, baseline: 45 },
  { date: "2025-01-01", value: 82, baseline: 45 },
  { date: "2025-01-15", value: 88, baseline: 45 },
  { date: "2025-02-01", value: 92, baseline: 45 },
  { date: "2025-02-10", value: 95, baseline: 45 },
];

export const clinicalNotes: ClinicalNote[] = [
  { id: "cn1", patientId: "p1", authorId: "u1", authorName: "BS. Nguyen Van An", content: "Bệnh nhân tiến triển tốt. ROM gối tăng từ 45 lên 95 độ. Tiếp tục phác đồ hiện tại.", createdAt: "2025-02-10T15:00:00" },
  { id: "cn2", patientId: "p1", authorId: "u1", authorName: "BS. Nguyen Van An", content: "Bắt đầu giai đoạn 2 phục hồi. Tăng cường bài tập chịu lực.", createdAt: "2025-01-15T10:00:00" },
  { id: "cn3", patientId: "p3", authorId: "u1", authorName: "BS. Nguyen Van An", content: "Bệnh nhân bỏ tập 5 ngày. Cần liên hệ động viên và điều chỉnh phác đồ.", createdAt: "2025-02-08T09:00:00" },
];

export const notifications: AppNotification[] = [
  { id: "n1", type: "compliance_alert", title: "Cảnh báo bỏ tập", message: "Phạm Đức Minh đã bỏ tập 5 ngày liên tiếp", isRead: false, createdAt: "2025-02-10T08:00:00", patientId: "p3", patientName: "Phạm Đức Minh" },
  { id: "n2", type: "compliance_alert", title: "Tập sai tư thế", message: "Đặng Quốc Bảo tập sai tư thế bài Căng cơ bắp chân (3 lần)", isRead: false, createdAt: "2025-02-09T16:00:00", patientId: "p7", patientName: "Đặng Quốc Bảo" },
  { id: "n3", type: "appointment", title: "Lịch hẹn sắp tới", message: "Bạn có lịch hẹn với Trần Thị Mai lúc 09:00 ngày 12/02", isRead: false, createdAt: "2025-02-11T07:00:00", patientId: "p1", patientName: "Trần Thị Mai" },
  { id: "n4", type: "video_review", title: "Video cần review", message: "Võ Văn Tài đã gửi video bài tập Gập gối", isRead: true, createdAt: "2025-02-10T14:30:00", patientId: "p5", patientName: "Võ Văn Tài" },
  { id: "n5", type: "system", title: "Cập nhật hệ thống", message: "Phiên bản mới đã được cập nhật với tính năng AI Posture Score cải tiến", isRead: true, createdAt: "2025-02-08T12:00:00" },
  { id: "n6", type: "appointment", title: "Lịch hẹn bị hủy", message: "Nguyễn Thị Lan đã hủy lịch hẹn ngày 10/02", isRead: true, createdAt: "2025-02-09T10:00:00", patientId: "p4", patientName: "Nguyễn Thị Lan" },
];

export const videoReviews: VideoReview[] = [
  { id: "v1", patientId: "p1", patientName: "Tran Thi Mai", exerciseId: "e1", exerciseName: "Gập gối", videoUrl: "/videos/patient-1-knee.mp4", referenceVideoUrl: "/videos/knee-flexion.mp4", submittedAt: "2025-02-10T14:30:00", status: "pending" },
  { id: "v2", patientId: "p5", patientName: "Vo Van Tai", exerciseId: "e1", exerciseName: "Gập gối", videoUrl: "/videos/patient-5-knee.mp4", referenceVideoUrl: "/videos/knee-flexion.mp4", submittedAt: "2025-02-10T08:55:00", status: "pending" },
  { id: "v3", patientId: "p2", patientName: "Le Hoang Nam", exerciseId: "e6", exerciseName: "Plank cơ bản", videoUrl: "/videos/patient-2-plank.mp4", referenceVideoUrl: "/videos/plank.mp4", submittedAt: "2025-02-09T10:30:00", reviewedAt: "2025-02-09T16:00:00", status: "reviewed", feedback: "Tư thế tốt. Cần giữ lưng thẳng hơn 1 chút.", annotations: [{ id: "an1", timestampSeconds: 15, note: "Lưng hơi võng xuống", type: "improvement" }] },
  { id: "v4", patientId: "p7", patientName: "Dang Quoc Bao", exerciseId: "e5", exerciseName: "Căng cơ bắp chân", videoUrl: "/videos/patient-7-calf.mp4", referenceVideoUrl: "/videos/calf-stretch.mp4", submittedAt: "2025-02-08T11:00:00", reviewedAt: "2025-02-08T15:00:00", status: "reviewed", feedback: "Tư thế sai. Cần hướng dẫn lại.", annotations: [{ id: "an2", timestampSeconds: 8, note: "Chân chưa thẳng", type: "error" }, { id: "an3", timestampSeconds: 20, note: "Giữ tốt", type: "good" }] },
];


export const complianceData: ComplianceDataPoint[] = [
  { week: "T1-W1", rate: 65 },
  { week: "T1-W2", rate: 70 },
  { week: "T1-W3", rate: 68 },
  { week: "T1-W4", rate: 75 },
  { week: "T2-W1", rate: 78 },
  { week: "T2-W2", rate: 80 },
  { week: "T2-W3", rate: 82 },
  { week: "T2-W4", rate: 79 },
  { week: "T3-W1", rate: 85 },
  { week: "T3-W2", rate: 83 },
  { week: "T3-W3", rate: 87 },
  { week: "T3-W4", rate: 84 },
];

export const treatmentHistory: TreatmentHistoryEntry[] = [
  { id: "th1", protocolName: "Phục hồi ACL - Giai đoạn 1", startDate: "2024-11-01", endDate: "2024-12-15", status: "completed", notes: "Hoàn thành tốt" },
  { id: "th2", protocolName: "Phục hồi ACL - Giai đoạn 2", startDate: "2024-12-16", status: "active", notes: "Đang thực hiện" },
];

export const staffUsers: User[] = [
  { id: "u1", email: "dr.nguyen@hopita.vn", fullName: "BS. Nguyen Van An", phone: "0901234567", role: "doctor", facilityId: "f1", createdAt: "2024-01-15" },
  { id: "u2", email: "ktv.tran@hopita.vn", fullName: "KTV. Tran Minh Tu", phone: "0902345678", role: "ktv", facilityId: "f1", createdAt: "2024-02-01" },
  { id: "u3", email: "admin@hopita.vn", fullName: "Admin Hopita", phone: "0903456789", role: "admin", createdAt: "2024-01-01" },
  { id: "u4", email: "dr.le@hopita.vn", fullName: "BS. Le Thi Hong", phone: "0904567890", role: "doctor", facilityId: "f1", createdAt: "2024-03-10" },
  { id: "u5", email: "ktv.pham@hopita.vn", fullName: "KTV. Pham Van Duc", phone: "0905678901", role: "ktv", facilityId: "f2", createdAt: "2024-05-20" },
];

export const dashboardStats = {
  totalPatients: 8,
  activePatients: 5,
  completedPatients: 1,
  attentionPatients: 2,
  upcomingAppointments: 5,
  complianceRate: 74,
  alertsCount: 3,
};

export const progressOverview = [
  { month: "T9", improved: 12, stable: 5, declined: 1 },
  { month: "T10", improved: 15, stable: 4, declined: 2 },
  { month: "T11", improved: 18, stable: 6, declined: 1 },
  { month: "T12", improved: 14, stable: 8, declined: 3 },
  { month: "T1", improved: 20, stable: 5, declined: 1 },
  { month: "T2", improved: 16, stable: 7, declined: 2 },
];
