import {
  Patient,
  Exercise,
  Protocol,
  ExerciseSession,
  Appointment,
  RomDataPoint,
  ClinicalNote,
  AppNotification,
  VideoReview,
  Facility,
  ComplianceDataPoint,
  TreatmentHistoryEntry,
  User,
} from "@/types";

export const currentUser: User = {
  id: "u1",
  email: "dr.nguyen@hopita.vn",
  fullName: "BS. Nguyen Van An",
  phone: "0901234567",
  avatarUrl: undefined,
  role: "doctor",
  facilityId: "f1",
  createdAt: "2024-01-15",
};

export const patients: Patient[] = [
  {
    id: "p1",
    fullName: "Tran Thi Mai",
    email: "mai.tran@gmail.com",
    phone: "0912345678",
    dateOfBirth: "1985-03-15",
    gender: "female",
    diagnosis: "Phuc hoi sau phau thuat day chang cheo truoc (ACL)",
    status: "active",
    assignedDoctorId: "u1",
    assignedDoctorName: "BS. Nguyen Van An",
    currentProtocolId: "pr1",
    currentProtocolName: "Phuc hoi ACL - Giai doan 2",
    complianceRate: 85,
    lastSessionAt: "2025-02-10T14:30:00",
    createdAt: "2024-11-01",
  },
  {
    id: "p2",
    fullName: "Le Hoang Nam",
    email: "nam.le@gmail.com",
    phone: "0923456789",
    dateOfBirth: "1990-07-22",
    gender: "male",
    diagnosis: "Dau lung man tinh - Thoat vi dia dem L4-L5",
    status: "active",
    assignedDoctorId: "u1",
    assignedDoctorName: "BS. Nguyen Van An",
    currentProtocolId: "pr2",
    currentProtocolName: "Phuc hoi cot song that lung",
    complianceRate: 72,
    lastSessionAt: "2025-02-09T10:00:00",
    createdAt: "2024-12-15",
  },
  {
    id: "p3",
    fullName: "Pham Duc Minh",
    email: "minh.pham@gmail.com",
    phone: "0934567890",
    dateOfBirth: "1978-11-30",
    gender: "male",
    diagnosis: "Dong cung khop vai (Frozen shoulder)",
    status: "attention",
    assignedDoctorId: "u1",
    assignedDoctorName: "BS. Nguyen Van An",
    currentProtocolId: "pr3",
    currentProtocolName: "Phuc hoi khop vai",
    complianceRate: 45,
    lastSessionAt: "2025-02-05T09:00:00",
    createdAt: "2024-10-20",
    notes: "Benh nhan bo tap 5 ngay lien tiep",
  },
  {
    id: "p4",
    fullName: "Nguyen Thi Lan",
    email: "lan.nguyen@gmail.com",
    phone: "0945678901",
    dateOfBirth: "1995-05-10",
    gender: "female",
    diagnosis: "Chan thuong co vai khi choi cau long",
    status: "completed",
    assignedDoctorId: "u1",
    assignedDoctorName: "BS. Nguyen Van An",
    complianceRate: 95,
    lastSessionAt: "2025-01-28T16:00:00",
    createdAt: "2024-09-01",
  },
  {
    id: "p5",
    fullName: "Vo Van Tai",
    email: "tai.vo@gmail.com",
    phone: "0956789012",
    dateOfBirth: "1982-01-25",
    gender: "male",
    diagnosis: "Phuc hoi sau thay khop goi",
    status: "active",
    assignedDoctorId: "u1",
    assignedDoctorName: "BS. Nguyen Van An",
    currentProtocolId: "pr4",
    currentProtocolName: "Phuc hoi thay khop goi - Giai doan 1",
    complianceRate: 90,
    lastSessionAt: "2025-02-10T08:30:00",
    createdAt: "2025-01-10",
  },
  {
    id: "p6",
    fullName: "Hoang Thi Huong",
    email: "huong.hoang@gmail.com",
    phone: "0967890123",
    dateOfBirth: "1988-09-18",
    gender: "female",
    diagnosis: "Hoi chung ong co tay (Carpal tunnel)",
    status: "active",
    assignedDoctorId: "u1",
    assignedDoctorName: "BS. Nguyen Van An",
    currentProtocolId: "pr5",
    currentProtocolName: "Phuc hoi ong co tay",
    complianceRate: 78,
    lastSessionAt: "2025-02-09T15:00:00",
    createdAt: "2025-01-05",
  },
  {
    id: "p7",
    fullName: "Dang Quoc Bao",
    email: "bao.dang@gmail.com",
    phone: "0978901234",
    dateOfBirth: "2000-12-05",
    gender: "male",
    diagnosis: "Bong gân co chan sau choi bong da",
    status: "attention",
    assignedDoctorId: "u1",
    assignedDoctorName: "BS. Nguyen Van An",
    currentProtocolId: "pr6",
    currentProtocolName: "Phuc hoi co chan",
    complianceRate: 35,
    lastSessionAt: "2025-02-03T11:00:00",
    createdAt: "2025-01-20",
    notes: "Benh nhan tap sai tu the nhieu lan",
  },
  {
    id: "p8",
    fullName: "Bui Thi Thanh",
    email: "thanh.bui@gmail.com",
    phone: "0989012345",
    dateOfBirth: "1972-04-08",
    gender: "female",
    diagnosis: "Thoai hoa khop goi",
    status: "active",
    assignedDoctorId: "u1",
    assignedDoctorName: "BS. Nguyen Van An",
    currentProtocolId: "pr7",
    currentProtocolName: "Bai tap thoai hoa khop goi",
    complianceRate: 88,
    lastSessionAt: "2025-02-10T10:00:00",
    createdAt: "2024-08-15",
  },
];

export const exercises: Exercise[] = [
  {
    id: "e1",
    name: "Gap goi (Knee Flexion)",
    description: "Gap goi tu tu de tang bien do van dong khop goi",
    videoUrl: "/videos/knee-flexion.mp4",
    durationSeconds: 30,
    repetitions: 15,
    setsPerDay: 3,
    safetyNotes: "Dung gap qua 90 do trong giai doan dau",
    category: "Khop goi",
  },
  {
    id: "e2",
    name: "Duoi goi (Knee Extension)",
    description: "Duoi thang chan de tang suc manh co tu dau",
    videoUrl: "/videos/knee-extension.mp4",
    durationSeconds: 30,
    repetitions: 12,
    setsPerDay: 3,
    safetyNotes: "Giu lung thang, khong uon cong",
    category: "Khop goi",
  },
  {
    id: "e3",
    name: "Nang chan thang (Straight Leg Raise)",
    description: "Nang chan thang khi nam ngua de tang suc co",
    videoUrl: "/videos/slr.mp4",
    durationSeconds: 20,
    repetitions: 10,
    setsPerDay: 3,
    category: "Khop goi",
  },
  {
    id: "e4",
    name: "Xoay vai (Shoulder Rotation)",
    description: "Xoay vai theo vong tron de tang ROM",
    videoUrl: "/videos/shoulder-rotation.mp4",
    durationSeconds: 25,
    repetitions: 10,
    setsPerDay: 2,
    safetyNotes: "Khong xoay qua nhanh",
    category: "Khop vai",
  },
  {
    id: "e5",
    name: "Cang co bap chan (Calf Stretch)",
    description: "Keo gian co bap chan de giam dau va tang do linh hoat",
    videoUrl: "/videos/calf-stretch.mp4",
    durationSeconds: 30,
    repetitions: 8,
    setsPerDay: 2,
    category: "Co chan",
  },
  {
    id: "e6",
    name: "Plank co ban",
    description: "Bai tap plank tang suc manh co loi (core)",
    videoUrl: "/videos/plank.mp4",
    durationSeconds: 30,
    repetitions: 3,
    setsPerDay: 2,
    safetyNotes: "Giu lung thang, khong vo lung",
    category: "Cot song",
  },
  {
    id: "e7",
    name: "Cat-Cow Stretch",
    description: "Keo gian cot song theo kieu meo-bo",
    videoUrl: "/videos/cat-cow.mp4",
    durationSeconds: 20,
    repetitions: 10,
    setsPerDay: 2,
    category: "Cot song",
  },
  {
    id: "e8",
    name: "Bai tap co tay (Wrist Flexion)",
    description: "Gap duoi co tay de phuc hoi hoi chung ong co tay",
    videoUrl: "/videos/wrist-flexion.mp4",
    durationSeconds: 15,
    repetitions: 15,
    setsPerDay: 3,
    category: "Co tay",
  },
];

export const protocols: Protocol[] = [
  {
    id: "pr1",
    name: "Phuc hoi ACL - Giai doan 2",
    description: "Phac do phuc hoi sau phau thuat day chang cheo truoc, giai doan 2 (tuan 4-8)",
    targetCondition: "ACL Reconstruction",
    isTemplate: true,
    exercises: [
      { exerciseId: "e1", exerciseName: "Gap goi", sets: 3, reps: 15, durationSeconds: 30, frequency: "2 lan/ngay", order: 1 },
      { exerciseId: "e2", exerciseName: "Duoi goi", sets: 3, reps: 12, durationSeconds: 30, frequency: "2 lan/ngay", order: 2 },
      { exerciseId: "e3", exerciseName: "Nang chan thang", sets: 3, reps: 10, durationSeconds: 20, frequency: "1 lan/ngay", order: 3 },
    ],
    durationWeeks: 4,
    createdBy: "BS. Nguyen Van An",
    createdAt: "2024-10-01",
    assignedPatientCount: 3,
  },
  {
    id: "pr2",
    name: "Phuc hoi cot song that lung",
    description: "Phac do cho benh nhan thoat vi dia dem L4-L5",
    targetCondition: "Lumbar Disc Herniation",
    isTemplate: true,
    exercises: [
      { exerciseId: "e6", exerciseName: "Plank co ban", sets: 2, reps: 3, durationSeconds: 30, frequency: "1 lan/ngay", order: 1 },
      { exerciseId: "e7", exerciseName: "Cat-Cow Stretch", sets: 2, reps: 10, durationSeconds: 20, frequency: "2 lan/ngay", order: 2 },
    ],
    durationWeeks: 6,
    createdBy: "BS. Nguyen Van An",
    createdAt: "2024-11-15",
    assignedPatientCount: 2,
  },
  {
    id: "pr3",
    name: "Phuc hoi khop vai",
    description: "Phac do cho dong cung khop vai (frozen shoulder)",
    targetCondition: "Frozen Shoulder",
    isTemplate: true,
    exercises: [
      { exerciseId: "e4", exerciseName: "Xoay vai", sets: 2, reps: 10, durationSeconds: 25, frequency: "3 lan/ngay", order: 1 },
    ],
    durationWeeks: 8,
    createdBy: "BS. Nguyen Van An",
    createdAt: "2024-09-20",
    assignedPatientCount: 1,
  },
  {
    id: "pr4",
    name: "Phuc hoi thay khop goi - Giai doan 1",
    description: "Phac do giai doan dau sau phau thuat thay khop goi (tuan 1-4)",
    targetCondition: "Total Knee Replacement",
    isTemplate: true,
    exercises: [
      { exerciseId: "e1", exerciseName: "Gap goi", sets: 2, reps: 10, durationSeconds: 30, frequency: "3 lan/ngay", order: 1 },
      { exerciseId: "e2", exerciseName: "Duoi goi", sets: 2, reps: 10, durationSeconds: 30, frequency: "3 lan/ngay", order: 2 },
    ],
    durationWeeks: 4,
    createdBy: "BS. Nguyen Van An",
    createdAt: "2025-01-10",
    assignedPatientCount: 1,
  },
  {
    id: "pr5",
    name: "Phuc hoi ong co tay",
    description: "Phac do cho hoi chung ong co tay (carpal tunnel)",
    targetCondition: "Carpal Tunnel Syndrome",
    isTemplate: false,
    exercises: [
      { exerciseId: "e8", exerciseName: "Bai tap co tay", sets: 3, reps: 15, durationSeconds: 15, frequency: "3 lan/ngay", order: 1 },
    ],
    durationWeeks: 6,
    createdBy: "BS. Nguyen Van An",
    createdAt: "2025-01-05",
    assignedPatientCount: 1,
  },
];

export const sessions: ExerciseSession[] = [
  { id: "s1", patientId: "p1", patientName: "Tran Thi Mai", exerciseId: "e1", exerciseName: "Gap goi", scheduledAt: "2025-02-10T08:00:00", completedAt: "2025-02-10T08:25:00", status: "completed", score: 88, accuracy: 92, postureScore: 85, durationSeconds: 1500, romValue: 95 },
  { id: "s2", patientId: "p1", patientName: "Tran Thi Mai", exerciseId: "e2", exerciseName: "Duoi goi", scheduledAt: "2025-02-10T08:30:00", completedAt: "2025-02-10T08:50:00", status: "completed", score: 90, accuracy: 95, postureScore: 88, durationSeconds: 1200, romValue: 170 },
  { id: "s3", patientId: "p2", patientName: "Le Hoang Nam", exerciseId: "e6", exerciseName: "Plank co ban", scheduledAt: "2025-02-10T09:00:00", status: "pending" },
  { id: "s4", patientId: "p3", patientName: "Pham Duc Minh", exerciseId: "e4", exerciseName: "Xoay vai", scheduledAt: "2025-02-10T10:00:00", status: "skipped" },
  { id: "s5", patientId: "p5", patientName: "Vo Van Tai", exerciseId: "e1", exerciseName: "Gap goi", scheduledAt: "2025-02-10T08:30:00", completedAt: "2025-02-10T08:55:00", status: "completed", score: 92, accuracy: 94, postureScore: 90, durationSeconds: 1500, romValue: 85 },
  { id: "s6", patientId: "p7", patientName: "Dang Quoc Bao", exerciseId: "e5", exerciseName: "Cang co bap chan", scheduledAt: "2025-02-10T11:00:00", status: "skipped" },
];

export const appointments: Appointment[] = [
  { id: "a1", patientId: "p1", patientName: "Tran Thi Mai", doctorId: "u1", doctorName: "BS. Nguyen Van An", scheduledAt: "2025-02-12T09:00:00", durationMinutes: 30, status: "scheduled", type: "followup", notes: "Tai kham sau 4 tuan tap" },
  { id: "a2", patientId: "p3", patientName: "Pham Duc Minh", doctorId: "u1", doctorName: "BS. Nguyen Van An", scheduledAt: "2025-02-12T10:00:00", durationMinutes: 45, status: "confirmed", type: "telehealth", meetingUrl: "https://meet.hopita.vn/room-123" },
  { id: "a3", patientId: "p5", patientName: "Vo Van Tai", doctorId: "u1", doctorName: "BS. Nguyen Van An", scheduledAt: "2025-02-13T14:00:00", durationMinutes: 30, status: "scheduled", type: "followup" },
  { id: "a4", patientId: "p7", patientName: "Dang Quoc Bao", doctorId: "u1", doctorName: "BS. Nguyen Van An", scheduledAt: "2025-02-14T08:30:00", durationMinutes: 60, status: "scheduled", type: "initial", notes: "Danh gia lan dau" },
  { id: "a5", patientId: "p2", patientName: "Le Hoang Nam", doctorId: "u1", doctorName: "BS. Nguyen Van An", scheduledAt: "2025-02-15T11:00:00", durationMinutes: 30, status: "scheduled", type: "telehealth", meetingUrl: "https://meet.hopita.vn/room-456" },
];

export const romData: RomDataPoint[] = [
  { date: "2024-11-01", value: 45, baseline: 45 },
  { date: "2024-11-15", value: 55, baseline: 45 },
  { date: "2024-12-01", value: 68, baseline: 45 },
  { date: "2024-12-15", value: 75, baseline: 45 },
  { date: "2025-01-01", value: 82, baseline: 45 },
  { date: "2025-01-15", value: 88, baseline: 45 },
  { date: "2025-02-01", value: 92, baseline: 45 },
  { date: "2025-02-10", value: 95, baseline: 45 },
];

export const clinicalNotes: ClinicalNote[] = [
  { id: "cn1", patientId: "p1", authorId: "u1", authorName: "BS. Nguyen Van An", content: "Benh nhan tien trien tot. ROM goi tang tu 45 len 95 do. Tiep tuc phac do hien tai.", createdAt: "2025-02-10T15:00:00" },
  { id: "cn2", patientId: "p1", authorId: "u1", authorName: "BS. Nguyen Van An", content: "Bat dau giai doan 2 phuc hoi. Tang cuong bai tap chiu luc.", createdAt: "2025-01-15T10:00:00" },
  { id: "cn3", patientId: "p3", authorId: "u1", authorName: "BS. Nguyen Van An", content: "Benh nhan bo tap 5 ngay. Can lien he dong vien va dieu chinh phac do.", createdAt: "2025-02-08T09:00:00" },
];

export const notifications: AppNotification[] = [
  { id: "n1", type: "compliance_alert", title: "Canh bao bo tap", message: "Pham Duc Minh da bo tap 5 ngay lien tiep", isRead: false, createdAt: "2025-02-10T08:00:00", patientId: "p3", patientName: "Pham Duc Minh" },
  { id: "n2", type: "compliance_alert", title: "Tap sai tu the", message: "Dang Quoc Bao tap sai tu the bai Cang co bap chan (3 lan)", isRead: false, createdAt: "2025-02-09T16:00:00", patientId: "p7", patientName: "Dang Quoc Bao" },
  { id: "n3", type: "appointment", title: "Lich hen sap toi", message: "Ban co lich hen voi Tran Thi Mai luc 09:00 ngay 12/02", isRead: false, createdAt: "2025-02-11T07:00:00", patientId: "p1", patientName: "Tran Thi Mai" },
  { id: "n4", type: "video_review", title: "Video can review", message: "Vo Van Tai da gui video bai tap Gap goi", isRead: true, createdAt: "2025-02-10T14:30:00", patientId: "p5", patientName: "Vo Van Tai" },
  { id: "n5", type: "system", title: "Cap nhat he thong", message: "Phien ban moi da duoc cap nhat voi tinh nang AI Posture Score cai tien", isRead: true, createdAt: "2025-02-08T12:00:00" },
  { id: "n6", type: "appointment", title: "Lich hen bi huy", message: "Nguyen Thi Lan da huy lich hen ngay 10/02", isRead: true, createdAt: "2025-02-09T10:00:00", patientId: "p4", patientName: "Nguyen Thi Lan" },
];

export const videoReviews: VideoReview[] = [
  { id: "v1", patientId: "p1", patientName: "Tran Thi Mai", exerciseId: "e1", exerciseName: "Gap goi", videoUrl: "/videos/patient-1-knee.mp4", referenceVideoUrl: "/videos/knee-flexion.mp4", submittedAt: "2025-02-10T14:30:00", status: "pending" },
  { id: "v2", patientId: "p5", patientName: "Vo Van Tai", exerciseId: "e1", exerciseName: "Gap goi", videoUrl: "/videos/patient-5-knee.mp4", referenceVideoUrl: "/videos/knee-flexion.mp4", submittedAt: "2025-02-10T08:55:00", status: "pending" },
  { id: "v3", patientId: "p2", patientName: "Le Hoang Nam", exerciseId: "e6", exerciseName: "Plank co ban", videoUrl: "/videos/patient-2-plank.mp4", referenceVideoUrl: "/videos/plank.mp4", submittedAt: "2025-02-09T10:30:00", reviewedAt: "2025-02-09T16:00:00", status: "reviewed", feedback: "Tu the tot. Can giu lung thang hon 1 chut.", annotations: [{ id: "an1", timestampSeconds: 15, note: "Lung hoi vo xuong", type: "improvement" }] },
  { id: "v4", patientId: "p7", patientName: "Dang Quoc Bao", exerciseId: "e5", exerciseName: "Cang co bap chan", videoUrl: "/videos/patient-7-calf.mp4", referenceVideoUrl: "/videos/calf-stretch.mp4", submittedAt: "2025-02-08T11:00:00", reviewedAt: "2025-02-08T15:00:00", status: "reviewed", feedback: "Tu the sai. Can huong dan lai.", annotations: [{ id: "an2", timestampSeconds: 8, note: "Chan chua thang", type: "error" }, { id: "an3", timestampSeconds: 20, note: "Giu tot", type: "good" }] },
];

export const facilities: Facility[] = [
  { id: "f1", name: "Benh vien Phuc hoi chuc nang TP.HCM", address: "150 Nguyen Luong Bang, Q.7, TP.HCM", phone: "028 1234 5678", doctorCount: 12, patientCount: 156, createdAt: "2024-01-01" },
  { id: "f2", name: "Phong kham Vat ly tri lieu ABC", address: "25 Le Duan, Q.1, TP.HCM", phone: "028 2345 6789", doctorCount: 5, patientCount: 48, createdAt: "2024-03-15" },
  { id: "f3", name: "Benh vien Cho Don", address: "67 Tran Hung Dao, Q.5, TP.HCM", phone: "028 3456 7890", doctorCount: 8, patientCount: 92, createdAt: "2024-06-01" },
];

export const complianceData: ComplianceDataPoint[] = [
  { week: "T1-W1", rate: 65 },
  { week: "T1-W2", rate: 70 },
  { week: "T1-W3", rate: 68 },
  { week: "T1-W4", rate: 75 },
  { week: "T2-W1", rate: 78 },
  { week: "T2-W2", rate: 80 },
  { week: "T2-W3", rate: 82 },
  { week: "T2-W4", rate: 79 },
  { week: "T3-W1", rate: 85 },
  { week: "T3-W2", rate: 83 },
  { week: "T3-W3", rate: 87 },
  { week: "T3-W4", rate: 84 },
];

export const treatmentHistory: TreatmentHistoryEntry[] = [
  { id: "th1", protocolName: "Phuc hoi ACL - Giai doan 1", startDate: "2024-11-01", endDate: "2024-12-15", status: "completed", notes: "Hoan thanh tot" },
  { id: "th2", protocolName: "Phuc hoi ACL - Giai doan 2", startDate: "2024-12-16", status: "active", notes: "Dang thuc hien" },
];

export const staffUsers: User[] = [
  { id: "u1", email: "dr.nguyen@hopita.vn", fullName: "BS. Nguyen Van An", phone: "0901234567", role: "doctor", facilityId: "f1", createdAt: "2024-01-15" },
  { id: "u2", email: "ktv.tran@hopita.vn", fullName: "KTV. Tran Minh Tu", phone: "0902345678", role: "ktv", facilityId: "f1", createdAt: "2024-02-01" },
  { id: "u3", email: "admin@hopita.vn", fullName: "Admin Hopita", phone: "0903456789", role: "admin", createdAt: "2024-01-01" },
  { id: "u4", email: "dr.le@hopita.vn", fullName: "BS. Le Thi Hong", phone: "0904567890", role: "doctor", facilityId: "f1", createdAt: "2024-03-10" },
  { id: "u5", email: "ktv.pham@hopita.vn", fullName: "KTV. Pham Van Duc", phone: "0905678901", role: "ktv", facilityId: "f2", createdAt: "2024-05-20" },
];

export const dashboardStats = {
  totalPatients: 8,
  activePatients: 5,
  completedPatients: 1,
  attentionPatients: 2,
  upcomingAppointments: 5,
  complianceRate: 74,
  alertsCount: 3,
};

export const progressOverview = [
  { month: "T9", improved: 12, stable: 5, declined: 1 },
  { month: "T10", improved: 15, stable: 4, declined: 2 },
  { month: "T11", improved: 18, stable: 6, declined: 1 },
  { month: "T12", improved: 14, stable: 8, declined: 3 },
  { month: "T1", improved: 20, stable: 5, declined: 1 },
  { month: "T2", improved: 16, stable: 7, declined: 2 },
];
